apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-simple
  namespace: arc
  labels:
    app: grafana-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-simple
  template:
    metadata:
      labels:
        app: grafana-simple
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-simple
  namespace: arc
  labels:
    app: grafana-simple
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana-simple