---
# PersistentVolumeClaim for Factory Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factory-data-pvc
  namespace: smart-factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
---
# PersistentVolumeClaim for Robot Control Data  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robot-data-pvc
  namespace: smart-factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default
---
# PersistentVolumeClaim for SCADA Historical Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scada-data-pvc
  namespace: smart-factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: default
---
# PersistentVolumeClaim for InfluxDB Time Series
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  namespace: smart-factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: default
---
# PersistentVolumeClaim for Redis Cache
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: smart-factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default