---
# Factory Simulator Service
apiVersion: v1
kind: Service
metadata:
  name: factory-simulator
  namespace: smart-factory
  labels:
    app: factory-simulator
    component: simulation
spec:
  selector:
    app: factory-simulator
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: websocket
      port: 8081  
      targetPort: 8081
  type: ClusterIP

---
# Robot Controller Service
apiVersion: v1
kind: Service
metadata:
  name: robot-controller
  namespace: smart-factory
  labels:
    app: robot-controller
    component: control
spec:
  selector:
    app: robot-controller
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: api
      port: 8083
      targetPort: 8083
  type: ClusterIP

---
# SCADA Dashboard Service  
apiVersion: v1
kind: Service
metadata:
  name: scada-dashboard
  namespace: smart-factory
  labels:
    app: scada-dashboard
    component: monitoring
spec:
  selector:
    app: scada-dashboard
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP

---
# InfluxDB Service
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: smart-factory
  labels:
    app: influxdb
    component: database
spec:
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: smart-factory
  labels:
    app: redis
    component: cache
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP

---
# Factory Dashboard LoadBalancer (External Access)
apiVersion: v1
kind: Service
metadata:
  name: factory-dashboard-lb
  namespace: smart-factory
  labels:
    app: factory-dashboard
    component: frontend
spec:
  selector:
    app: scada-dashboard
  ports:
    - name: scada
      port: 8080
      targetPort: 8084
      nodePort: 30080
    - name: factory
      port: 8081
      targetPort: 8080
      nodePort: 30081  
    - name: robots
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: LoadBalancer
  # In Azure Local, this will get an external IP from the cluster

---
# IoT Data Collector Service
apiVersion: v1
kind: Service
metadata:
  name: iot-collector
  namespace: smart-factory
  labels:
    app: iot-collector
    component: telemetry
spec:
  selector:
    app: iot-collector
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: http
      port: 8088
      targetPort: 8088
  type: ClusterIP

---
# Edge AI Processor Service
apiVersion: v1
kind: Service
metadata:
  name: edge-ai
  namespace: smart-factory
  labels:
    app: edge-ai
    component: ai
spec:
  selector:
    app: edge-ai
  ports:
    - name: api
      port: 8089
      targetPort: 8089
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP