# Azure ML Studio Environment Configuration
name: smartfactory-ml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.3.4
  - numpy=1.21.5
  - pandas=1.4.2
  - scikit-learn=1.1.1
  - tensorflow=2.8.0
  - pip:
    - azure-ai-ml==1.12.0
    - azure-identity==1.12.0
    - xgboost==1.7.3
    - joblib==1.1.0
    - matplotlib==3.5.1
    - seaborn==0.11.2
    - plotly==5.7.0
    - mlflow==2.1.1
    - azureml-core==1.48.0
    - azureml-mlflow==1.48.0